In [1]:
import requests

In [2]:
URL = "https://stephen-king-api.onrender.com/api/books"

res = requests.get(URL)

In [3]:
res

In [4]:
#res.json()

In [5]:
json_data = res.json()

In [6]:
import pandas as pd

df = pd.json_normalize(json_data["data"])
df

,id,Year,Title,handle,Publisher,ISBN,Pages,Notes,created_at,villains
0,1,1974,Carrie,carrie,Doubleday,978-0-385-08695-0,199,[],2023-11-13T23:48:47.848Z,"[{'name': 'Tina Blake', 'url': 'https://stephe..."
1,2,1975,Salem's Lot,salem-s-lot,Doubleday,978-0-385-00751-1,439,"[Nominee, World Fantasy Award, 1976[2]]",2023-11-13T23:48:48.098Z,"[{'name': 'Kurt Barlow', 'url': 'https://steph..."
2,3,1977,The Shining,the-shining,Doubleday,978-0-385-12167-5,447,"[Runner-up (4th place), Locus Award for Best F...",2023-11-13T23:48:48.219Z,"[{'name': 'Horace M. Derwent', 'url': 'https:/..."
3,4,1977,Rage,rage,Signet Books,978-0-451-07645-8,211,[Published under pseudonym Richard Bachman],2023-11-13T23:48:48.339Z,[]
4,5,1978,The Stand,the-stand,Doubleday,978-0-385-12168-2,823,"[Nominee, World Fantasy Award, 1979, Runner-up...",2023-11-13T23:48:48.477Z,"[{'name': 'Donald Merwin Elbert', 'url': 'http..."
...,...,...,...,...,...,...,...,...,...,...
59,60,2018,Elevation,elevation,Scribner,978-1-98210-231-9,144,[],2023-11-13T23:48:55.291Z,[]
60,61,2019,The Institute,the-institute,Scribner,978-1-98211-056-7,576,"[Nominee, British Fantasy Award's August Derle...",2023-11-13T23:48:55.457Z,"[{'name': 'Gladys Hickson', 'url': 'https://st..."
61,62,2021,Later,later,Hard Case Crime,978-1-78909-649-1,256,[],2023-11-13T23:48:55.579Z,[]
62,63,2021,Billy Summers,billy-summers,Scribner,978-1-982-17361-6,528,[],2023-11-13T23:48:55.753Z,[]
63,72,1979,The Roopak Zone,the-roopak-zone,Viking Press,978-0-670-26069697-5,428,"[Runner-up (2nd place), Locus Award for Best F...",2026-06-26T18:20:32.285Z,[]

In [7]:
df = df [["id", "Year", "Title", "ISBN"]]

In [8]:
df

    id  Year            Title                  ISBN
0    1  1974           Carrie     978-0-385-08695-0
1    2  1975      Salem's Lot     978-0-385-00751-1
2    3  1977      The Shining     978-0-385-12167-5
3    4  1977             Rage     978-0-451-07645-8
4    5  1978        The Stand     978-0-385-12168-2
..  ..   ...              ...                   ...
59  60  2018        Elevation     978-1-98210-231-9
60  61  2019    The Institute     978-1-98211-056-7
61  62  2021            Later     978-1-78909-649-1
62  63  2021    Billy Summers     978-1-982-17361-6
63  72  1979  The Roopak Zone  978-0-670-26069697-5

[64 rows x 4 columns]

In [9]:
url = "https://dogapi.dog/api-docs/v2/swagger.json"
res = requests.get(url)
res

In [10]:
json_data = res.json()

In [11]:
#json_dat

In [12]:
df = pd.json_normalize(json_data["info"])
df

,title,version,description,termsOfService,contact.email,license.name,license.url
0,API V2,1.0.0,The Dog API provides a wealth of information o...,https://dogapi.dog/terms,dev@dogapi.dog,MIT,https://github.com/kinduff/dogapi.dog/blob/mas...

In [13]:
url = "https://www.scrapethissite.com/pages/simple/"
res = requests.get(url)

In [14]:
res

In [15]:
if res.status_code == 200:
    print(res.headers)

with open("scrape_data/data1.html", "w", encoding="utf-8") as f:
    f.write(res.text)

{'Date': 'Sun, 25 Oct 2026 09:14:02 GMT', 'Content-Type': 'text/html; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Nel': '{"report_to":"heroku-nel","response_headers":["Via"],"max_age":3600,"success_fraction":0.01,"failure_fraction":0.1}', 'Report-To': '{"group":"heroku-nel","endpoints":[{"url":"https://nel.heroku.com/reports?s=I7J3yfPzZUx8URw423j%2Fxd20W0mM1dbvtkgtU08jZOM%3D\\u0026sid=67ff5de4-ad2b-4112-9289-cf96be89efed\\u0026ts=1792919642"}],"max_age":3600}', 'Reporting-Endpoints': 'heroku-nel="https://nel.heroku.com/reports?s=I7J3yfPzZUx8URw423j%2Fxd20W0mM1dbvtkgtU08jZOM%3D&sid=67ff5de4-ad2b-4112-9289-cf96be89efed&ts=1792919642"', 'Server': 'cloudflare', 'Via': '1.1 heroku-router', 'cf-cache-status': 'DYNAMIC', 'Content-Encoding': 'zstd', 'CF-RAY': 'a5001bd0588db0cc-DAC', 'alt-svc': 'h3=":443"; ma=86400'}

In [16]:
#pip install lxml

In [17]:
from bs4 import BeautifulSoup

with open("scrape_data/data1.html", "r") as f:
    html_content = f.read()
    
soup = BeautifulSoup(html_content, "lxml")

In [18]:
soup.find("h1")
#soup.h3

<h1>
                            Countries of the World: A Simple Example
                            <small>250 items</small>
</h1>

In [19]:
#soup.find_all("h3")
all_h3 = soup.find_all("h3")

all_countries = []

for h3 in all_h3:
    name = h3.get_text(strip=True)
    # print(h3.find_parent("div")["class"])
    population = h3.find_next("div").select("span.country-population")[0].get_text(strip=True)
    capital = h3.find_next("div").select("span.country-capital")[0].get_text(strip = True)
    all_countries.append([name, capital, population])

In [20]:
population

'11651858'

In [21]:
capital

'Harare'

In [22]:
name

'Zimbabwe'

In [23]:
#all_countries

In [24]:
import pandas as pd

df = pd.DataFrame(all_countries, columns=["name", "capital", "population"])
df

                     name           capital population
0                 Andorra  Andorra la Vella      84000
1    United Arab Emirates         Abu Dhabi    4975593
2             Afghanistan             Kabul   29121286
3     Antigua and Barbuda        St. John's      86754
4                Anguilla        The Valley      13254
..                    ...               ...        ...
245                 Yemen             Sanaa   23495361
246               Mayotte         Mamoudzou     159042
247          South Africa          Pretoria   49000000
248                Zambia            Lusaka   13460305
249              Zimbabwe            Harare   11651858

[250 rows x 3 columns]

In [25]:
df.to_csv("cleaned_data/data1.csv", index=False)

In [26]:
url = "https://quotes.toscrape.com/"
res = requests.get(url)
res

In [27]:
with open("scrape_data/data2.html", "w", encoding="utf-8") as f:
    f.write(res.text)

In [28]:
from bs4 import BeautifulSoup

with open("scrape_data/data2.html", "r", encoding="utf-8") as f:
    html_content = f.read()
    
soup = BeautifulSoup(html_content, "lxml")

In [29]:
soup.find("h1")

<h1>
<a href="/" style="text-decoration: none">Quotes to Scrape</a>
</h1>